import 'package:greend/products/product_model.dart';

final List<Product> beveragesProducts = [
  Product(
    id: 81,
    name: "Schweppes Ginger Ale, 355 mL Cans, 12 Pack",
    category: "Beverages",
    description: "12-pack of Schweppes Ginger Ale in 355 mL cans.",
    company: "Schweppes",
    ingredients: [],
    price: 6.99,
    imageUrl: "https://m.media-amazon.com/images/I/818o7mKCOvS._AC_SX569_.jpg",
    ecoRating: 5.3,
  ),
  Product(
    id: 82,
    name: "Pepsi cola Cans, 355 millilitre (Pack of 12)",
    category: "Beverages",
    description: "12-pack of Pepsi cola in 355 mL cans.",
    company: "Pepsi",
    ingredients: [],
    price: 7.49,
    imageUrl: "https://m.media-amazon.com/images/I/81cMcaUVCHL._AC_SX569_.jpg",
    ecoRating: 4.7,
  ),
  Product(
    id: 83,
    name: "7UP Soft Drink, 355 mL/12 fl. oz., Cans, 12 Pack",
    category: "Beverages",
    description: "12-pack of 7UP soft drink in 355 mL cans.",
    company: "7UP",
    ingredients: [],
    price: 7.48,
    imageUrl: "https://m.media-amazon.com/images/I/71UXMq1G6WS._AC_SX569_.jpg",
    ecoRating: 4.6,
  ),
  Product(
    id: 84,
    name: "Dr Pepper, 355 mL Cans, 12 Pack",
    category: "Beverages",
    description: "12-pack of Dr Pepper in 355 mL cans.",
    company: "Dr Pepper",
    ingredients: [],
    price: 6.99,
    imageUrl: "https://m.media-amazon.com/images/I/51w4Y82W7vL.__AC_SX300_SY300_QL70_ML2_.jpg",
    ecoRating: 4.6,
  ),
  Product(
    id: 85,
    name: "Coca-Cola Coke Classic, 355mL Cans, Pack of 12",
    category: "Beverages",
    description: "12-pack of Coca-Cola Classic in 355 mL cans.",
    company: "Coca-Cola",
    ingredients: [],
    price: 7.48,
    imageUrl: "https://m.media-amazon.com/images/I/814XdwTdknL._AC_SX569_.jpg",
    ecoRating: 4.3,
  ),
  Product(
    id: 86,
    name: "CELSIUS Sparkling Tropical Vibe, Zero Sugar Energy Drink, 335ml (Pack of 12)",
    category: "Beverages",
    description: "12-pack of CELSIUS Tropical Vibe zero sugar energy drink in 335 mL cans.",
    company: "CELSIUS",
    ingredients: [],
    price: 32.28,
    imageUrl: "https://m.media-amazon.com/images/I/81FqH1EqnDL.__AC_SX300_SY300_QL70_ML2_.jpg",
    ecoRating: 5.9,
  ),
  Product(
    id: 87,
    name: "Monster Energy, Zero Ultra, 473mL Cans, Pack of 12",
    category: "Beverages",
    description: "12-pack of Monster Energy Zero Ultra in 473 mL cans.",
    company: "Monster Energy",
    ingredients: [],
    price: 24.81,
    imageUrl: "https://m.media-amazon.com/images/I/913FhoiimGL.__AC_SY300_SX300_QL70_ML2_.jpg",
    ecoRating: 5.4,
  ),
  Product(
    id: 88,
    name: "ZOA Zero Sugar Energy Drinks, Wild Orange - 355ml (Pack of 12)",
    category: "Beverages",
    description: "12-pack of ZOA Zero Sugar Wild Orange energy drink in 355 mL cans.",
    company: "ZOA",
    ingredients: [],
    price: 20.98,
    imageUrl: "https://m.media-amazon.com/images/I/81taNH1jWHL.__AC_SX300_SY300_QL70_ML2_.jpg",
    ecoRating: 6.1,
  ),
  Product(
    id: 89,
    name: "Reign Energy, Orange Dreamsicle, 473mL Cans, Pack of 12",
    category: "Beverages",
    description: "12-pack of Reign Energy Orange Dreamsicle in 473 mL cans.",
    company: "Reign",
    ingredients: [],
    price: 28.99,
    imageUrl: "https://m.media-amazon.com/images/I/71X9GND5H0L._AC_SX522_.jpg",
    ecoRating: 5.5,
  ),
  Product(
    id: 90,
    name: "Red Bull Energy Drink, 250ml (12 Pack)",
    category: "Beverages",
    description: "12-pack of Red Bull Energy Drink in 250 mL cans.",
    company: "Red Bull",
    ingredients: [],
    price: 23.99,
    imageUrl: "https://m.media-amazon.com/images/I/71AFH2+YtkL._AC_SY300_SX300_.jpg",
    ecoRating: 5.0,
  ),
];