import 'package:greend/products/product_model.dart';

final List<Product> dairyAndEggsProducts = [
  Product(
    id: 1,
    name: "Great Value Large Eggs",
    category: "Dairy and Eggs",
    description: "Fresh large eggs from Great Value.",
    company: "Great Value",
    ingredients: ["Eggs"],
    price: 4.55,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_08930f74-5804-409a-ac0c-491a63a56a8f.jpeg",
    ecoRating: 6.0,
  ),
  Product(
    id: 2,
    name: "Golden Valley Large Eggs",
    category: "Dairy and Eggs",
    description: "Fresh large eggs from Golden Valley.",
    company: "Golden Valley",
    ingredients: ["Eggs"],
    price: 11.16,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_05cf0faa-a3b1-4b6e-826d-caa317253017.jpeg",
    ecoRating: 6.2,
  ),
  Product(
    id: 3,
    name: "Country Golden Yolks Large Free Range Eggs",
    category: "Dairy and Eggs",
    description: "Large free-range eggs from Country Golden Yolks.",
    company: "Country Golden Yolks",
    ingredients: ["Eggs"],
    price: 8.04,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_8d24557d-f514-4767-9e13-b07e6c1cd920.jpeg",
    ecoRating: 6.9,
  ),
  Product(
    id: 4,
    name: "Born 3 Eggs Large White Eggs",
    category: "Dairy and Eggs",
    description: "Large white eggs from Born 3 Eggs.",
    company: "Born 3 Eggs",
    ingredients: ["Eggs"],
    price: 10.54,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_8d24557d-f514-4767-9e13-b07e6c1cd920.jpeg",
    ecoRating: 6.0,
  ),
  Product(
    id: 5,
    name: "Dairyland 2% Milk",
    category: "Dairy and Eggs",
    description: "2% milk from Dairyland.",
    company: "Dairyland",
    ingredients: ["Milk"],
    price: 6.04,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_bafac8cb-792c-41ab-8e82-b275b625aab5.png",
    ecoRating: 5.3,
  ),
  Product(
    id: 6,
    name: "fairlife Milk 2% 1.5L",
    category: "Dairy and Eggs",
    description: "2% milk from Fairlife in a 1.5L bottle.",
    company: "Fairlife",
    ingredients: ["Milk"],
    price: 7.17,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_acb19054-8861-4fdf-959e-5cc0a8aa3fcf.jpeg",
    ecoRating: 6.0,
  ),
  Product(
    id: 7,
    name: "Natrel 2% Lactose Free",
    category: "Dairy and Eggs",
    description: "2% lactose-free milk from Natrel.",
    company: "Natrel",
    ingredients: [
      "Ultrafiltered partly skimmed milk with vitamin A palmitate",
      "Vitamin D3 added",
      "Water",
      "Lactase"
    ],
    price: 6.85,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_bbfb8cbd-3af5-4e6b-b439-a95022483765.jpeg",
    ecoRating: 5.3,
  ),
  Product(
    id: 8,
    name: "Great Value Old Cheddar Cheese",
    category: "Dairy and Eggs",
    description: "Old cheddar cheese from Great Value.",
    company: "Great Value",
    ingredients: [
      "Milk",
      "Modified milk ingredients",
      "Cream",
      "Salt",
      "Bacterial culture",
      "Microbial enzyme",
      "Annatto",
      "Calcium chloride"
    ],
    price: 7.60,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_91e6f869-a432-4b81-ba40-7d3ed8f6ed23.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 9,
    name: "Cracker Barrel Cheddar Coloured Old Cheese",
    category: "Dairy and Eggs",
    description: "Coloured old cheddar cheese from Cracker Barrel.",
    company: "Cracker Barrel",
    ingredients: [
      "Milk",
      "Modified milk ingredients",
      "Cream",
      "Salt",
      "Bacterial culture",
      "Calcium chloride",
      "Microbial enzyme",
      "Colour (annatto)",
      "Lipase"
    ],
    price: 9.56,
    imageUrl: "https://www.instacart.com/assets/domains/product-image/file/large_fbcf7b88-1911-489c-a970-b2ea2eedb8d3.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 10,
    name: "Armstrong Old Cheddar Bar",
    category: "Dairy and Eggs",
    description: "Old cheddar bar from Armstrong.",
    company: "Armstrong",
    ingredients: [
      "Pasteurized Milk",
      "Modified Milk Ingredients",
      "Salt",
      "Bacterial Culture",
      "Calcium Chloride",
      "Microbial Enzyme",
      "Annatto"
    ],
    price: 5.42,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_225d587d-4e2d-4862-aee7-98b7ea1a9aaa.jpg",
    ecoRating: 5.3,
  ),
];