import 'package:greend/products/product_model.dart';

final List<Product> frozenFoodProducts = [
  Product(
    id: 91,
    name: "Our Finest Cheese Puff Pastry",
    category: "Frozen Food",
    description: "Cheese puff pastry by Our Finest, perfect for baking and snacks.",
    company: "Our Finest",
    ingredients: [],
    price: 15.78,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_54ff2d70-2c3c-4baa-a3cb-daac80b8c81a.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 92,
    name: "Sunbulah Puff Pastry",
    category: "Frozen Food",
    description: "Flaky and buttery puff pastry by Sunbulah.",
    company: "Sunbulah",
    ingredients: [],
    price: 4.44,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_e50fcbb0-b751-4bf9-a900-f487e2ad37a2.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 93,
    name: "Great Value Patty Shells Puff Pastry",
    category: "Frozen Food",
    description: "Patty shells puff pastry by Great Value, ready to use.",
    company: "Great Value",
    ingredients: [],
    price: 4.87,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_02e2b951-b700-4738-91a6-a6f225e4cc33.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 94,
    name: "Ben & Jerry's Non-GMO With Fairtrade Ingredients Chocolate Therapy Ice Cream",
    category: "Frozen Food",
    description: "Rich and creamy chocolate ice cream by Ben & Jerry's, made with Fairtrade ingredients.",
    company: "Ben & Jerry",
    ingredients: [],
    price: 6.83,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_632b0243-b9c3-46c7-b133-355280cf4a2c.jpeg",
    ecoRating: 6.6,
  ),
  Product(
    id: 95,
    name: "Chapman's Original Dutch Chocolate Ice Cream",
    category: "Frozen Food",
    description: "Dutch chocolate ice cream by Chapman's, a rich and smooth treat.",
    company: "Chapman's",
    ingredients: [],
    price: 5.20,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_0cf90fd1-7910-4b06-a1c1-9759be75207d.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 96,
    name: "Breyers Chocolate Ice Cream",
    category: "Frozen Food",
    description: "Classic chocolate ice cream by Breyers.",
    company: "Breyers",
    ingredients: [],
    price: 5.42,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_6cd33f0e-3b43-42d0-8da5-51fb85c2e97b.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 97,
    name: "Natrel Lactose Free Completely Chocolate Ice Cream",
    category: "Frozen Food",
    description: "Lactose-free chocolate ice cream by Natrel.",
    company: "Natrel",
    ingredients: [],
    price: 6.51,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_a0fdfe9c-8427-4abe-b262-23d69673d5bd.jpeg",
    ecoRating: 4.6,
  ),
  Product(
    id: 98,
    name: "Great Value Potato & Cheddar Perogies",
    category: "Frozen Food",
    description: "Frozen potato and cheddar perogies by Great Value.",
    company: "Great Value",
    ingredients: [],
    price: 2.69,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_6b194d15-9277-4c07-b268-79af5521baaf.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 99,
    name: "CHEEMO Bacon & Cheese Potato Perogies",
    category: "Frozen Food",
    description: "Frozen bacon and cheese potato perogies by CHEEMO.",
    company: "CHEEMO",
    ingredients: [],
    price: 4.15,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_18332c5c-c0b2-4bbc-b639-c1c99acac354.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 100,
    name: "Bibigo Mandu Pork & Vegetable",
    category: "Frozen Food",
    description: "Frozen pork and vegetable dumplings by Bibigo.",
    company: "Bibigo",
    ingredients: [],
    price: 10.97,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_2af41987-5d03-45d5-9847-f84ca4a43bca.jpeg",
    ecoRating: 4.5,
  ),
];