import 'package:greend/products/product_model.dart';

final List<Product> hoodieSweaterProducts = [
  Product(
    id: 41,
    name: "Hanes Men’s Ultimate Cotton Heavyweight Pullover Hoodie Sweatshirt",
    category: "Hoodie/Sweater",
    description: "Heavyweight pullover hoodie sweatshirt made from ultimate cotton by Hanes.",
    company: "Hanes",
    ingredients: [],
    price: 33.99,
    imageUrl: "https://m.media-amazon.com/images/I/61JckjKagSL._AC_SX385_.jpg",
    ecoRating: 5.5,
  ),
  Product(
    id: 42,
    name: "Carhartt Mens Midweight Sleeve Logo Hooded Sweatshirt (Regular and Big & Tall Sizes)",
    category: "Hoodie/Sweater",
    description: "Midweight hooded sweatshirt with sleeve logo by Carhartt.",
    company: "Carhartt",
    ingredients: [],
    price: 84.99,
    imageUrl: "https://m.media-amazon.com/images/I/61mPjCyVZoL._AC_SX466_.jpg",
    ecoRating: 6.2,
  ),
  Product(
    id: 43,
    name: "Jerzees Men's Black Adult Pullover Hooded Sweatshirt",
    category: "Hoodie/Sweater",
    description: "Classic black adult pullover hoodie by Jerzees.",
    company: "Jerzees",
    ingredients: [],
    price: 23.94,
    imageUrl: "https://m.media-amazon.com/images/I/71ilUEU0MoL._AC_SY445_.jpg",
    ecoRating: 4.8,
  ),
  Product(
    id: 44,
    name: "Gildan Men's Heavy Blend Hooded Sweatshirt",
    category: "Hoodie/Sweater",
    description: "Heavy blend hooded sweatshirt by Gildan.",
    company: "Gildan",
    ingredients: [],
    price: 31.88,
    imageUrl: "https://m.media-amazon.com/images/I/61qTPaU7dYL._AC_SX466_.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 45,
    name: "JMIERR Mens Hoodies Pullover Casual Sweatshirts Long Sleeve Workout Drawstring Hoodie Gym Athletic Hooded with Pocket",
    category: "Hoodie/Sweater",
    description: "Casual long sleeve workout hoodie with drawstring by JMIERR.",
    company: "JMIERR",
    ingredients: [],
    price: 47.99,
    imageUrl: "https://m.media-amazon.com/images/I/61hcgWOefYL._AC_SY445_.jpg",
    ecoRating: 4.1,
  ),
  Product(
    id: 46,
    name: "Hanes Men’s EcoSmart Fleece Sweatshirt",
    category: "Hoodie/Sweater",
    description: "EcoSmart fleece sweatshirt by Hanes, made from sustainable materials.",
    company: "Hanes",
    ingredients: [],
    price: 22.38,
    imageUrl: "https://m.media-amazon.com/images/I/71fyw1U54GL._AC_SX466_.jpg",
    ecoRating: 6.9,
  ),
  Product(
    id: 47,
    name: "Fruit of the Loom Mens Eversoft Fleece Sweatshirts & Hoodies",
    category: "Hoodie/Sweater",
    description: "Eversoft fleece sweatshirt and hoodie by Fruit of the Loom.",
    company: "Fruit of the Loom",
    ingredients: [],
    price: 19.01,
    imageUrl: "https://m.media-amazon.com/images/I/71M+qLWDNOL._AC_SY445_.jpg",
    ecoRating: 5.8,
  ),
  Product(
    id: 48,
    name: "Amazon Essentials Mens Crewneck Sweater",
    category: "Hoodie/Sweater",
    description: "Classic crewneck sweater for men by Amazon Essentials.",
    company: "Amazon Essentials",
    ingredients: [],
    price: 25.30,
    imageUrl: "https://m.media-amazon.com/images/I/91nG7tYFJ4L._AC_SX385_.jpg",
    ecoRating: 5.1,
  ),
  Product(
    id: 49,
    name: "MAGCOMSEN Crewneck Sweatshirts for Men Fleece Lined Sweater Warm Sherpa Lined Pullover Thick Thermal Tops Winter",
    category: "Hoodie/Sweater",
    description: "Warm fleece-lined crewneck sweater by MAGCOMSEN for winter.",
    company: "MAGCOMSEN",
    ingredients: [],
    price: 59.98,
    imageUrl: "https://m.media-amazon.com/images/I/81Jxq7jJrvL._AC_SX342_.jpg",
    ecoRating: 4.5,
  ),
  Product(
    id: 50,
    name: "COOFANDY Men's Full Zip Cardigan Sweater Cable Knitted Slim Fit Zip Up Sweaters Long Sleeve Sweaters with Pockets",
    category: "Hoodie/Sweater",
    description: "Full-zip slim fit cardigan sweater with cable knit design by COOFANDY.",
    company: "COOFANDY",
    ingredients: [],
    price: 56.99,
    imageUrl: "https://m.media-amazon.com/images/I/81YbGE9v99L._AC_SX342_.jpg",
    ecoRating: 4.9,
  ),
];