import 'package:greend/products/product_model.dart';

final List<Product> menShirtsProducts = [
  Product(
    id: 21,
    name: "Jerzees Men's Long-Sleeve T-Shirt",
    category: "Shirts - Men",
    description: "Classic long-sleeve T-shirt for men by Jerzees.",
    company: "Jerzees",
    ingredients: ["50% Cotton", "50% Polyester"], 
    price: 16.03, 
    imageUrl: "https://m.media-amazon.com/images/I/71c7eRazT8S._AC_SX466_.jpg",
    ecoRating: 4.5,
  ),
  Product(
    id: 22,
    name: "Amazon Essentials Men's Slim-Fit Long-Sleeve Henley Shirt",
    category: "Shirts - Men",
    description: "Slim-fit long-sleeve Henley shirt from Amazon Essentials.",
    company: "Amazon Essentials",
    ingredients: ["100% Cotton"],
    price: 20.00,
    imageUrl: "https://m.media-amazon.com/images/I/916e0XF8LFL._AC_SX466_.jpg",
    ecoRating: 5.2,
  ),
  Product(
    id: 23,
    name: "Alimens & Gentle Men's Dress Shirts Long Sleeve Stretch Wrinkle-Free Formal Solid Button Down Shirt with Pocket",
    category: "Shirts - Men",
    description:
        "Wrinkle-free formal dress shirt by Alimens & Gentle with stretch and a pocket.",
    company: "Alimens & Gentle",
    ingredients: ["62% Cotton", "35% Polyester", "3% Spandex"],
    price: 29.99,
    imageUrl: "https://m.media-amazon.com/images/I/61P-fqPM9YL._AC_SX385_.jpg",
    ecoRating: 4.7,
  ),
  Product(
    id: 24,
    name: "Paul Jones Men's Long Sleeve Button Down Dress Shirts",
    category: "Shirts - Men",
    description: "Long sleeve button-down dress shirt from Paul Jones.",
    company: "PJ PAUL JONES",
    ingredients: ["65% Polyester", "35% Cotton"], 
    price: 49.99,
    imageUrl: "https://m.media-amazon.com/images/I/71OxuLakURL._AC_SX425_.jpg",
    ecoRating: 4.2,
  ),
  Product(
    id: 25,
    name: "Champion Men’s Champion Classic Jersey Graphic T-shirt",
    category: "Shirts - Men",
    description: "Classic jersey graphic T-shirt by Champion.",
    company: "Champion",
    ingredients: ["100% Cotton"],
    price: 22.49,
    imageUrl: "https://m.media-amazon.com/images/I/710mrytAbpL._AC_SX466_.jpg",
    ecoRating: 5.5,
  ),
  Product(
    id: 26,
    name: "Russell Athletic Mens Basic Cotton T-Shirt",
    category: "Shirts - Men",
    description: "Basic cotton T-shirt by Russell Athletic.",
    company: "Russell Athletic",
    ingredients: ["60% Cotton", "40% Polyester"],
    price: 12.84,
    imageUrl: "https://m.media-amazon.com/images/I/71F4P1t80EL._AC_SX466_.jpg",
    ecoRating: 4.7,
  ),
  Product(
    id: 27,
    name: "Under Armour Men's Gray Short-Sleeved Sporty T-Shirt in Medium",
    category: "Shirts - Men",
    description: "Sporty short-sleeved T-shirt by Under Armour.",
    company: "Under Armour",
    ingredients: ["60% Cotton", "40% Polyester"],
    price: 30.00,
    imageUrl: "https://m.media-amazon.com/images/I/41590kvBQ3L._AC_SX679_.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 28,
    name: "JMIERR Men's T-Shirt Casual Long Sleeve V Neck Slim Henley Shirts Classic Longline Muscle Gym Activewear Tees",
    category: "Shirts - Men",
    description: "Casual long-sleeve Henley shirt by JMIERR, perfect for gym or casual wear.",
    company: "JMIERR",
    ingredients: ["62% Polyester", "32% Cotton", "6% Elastane"],
    price: 31.99,
    imageUrl: "https://m.media-amazon.com/images/I/71rNWOdIMJL._AC_SY741_.jpg",
    ecoRating: 4.2,
  ),
  Product(
    id: 29,
    name: "ZSJR Mens Mock Neck T Shirts Pullover High Neck Turtleneck Premium Long Sleeve Sweaters for Men",
    category: "Shirts - Men",
    description: "Premium long sleeve turtleneck sweater by ZSJR.",
    company: "ZSJR",
    ingredients: ["100% Cotton"], 
    price: 6.89,
    imageUrl: "https://m.media-amazon.com/images/I/618PEf7JeAL._AC_SX569_.jpg",
    ecoRating: 4.7,
  ),
  Product(
    id: 30,
    name: "Men's Fleece Pullover Hoodie Vintage Corduroy Sweatshirts Men Stand Collared Tops Button-Up Shirts Outdoor Clothing",
    category: "Shirts - Men",
    description: "Vintage corduroy pullover hoodie for men.",
    company: "Generic",
    ingredients: ["100% Polyester"], 
    price: 15.99,
    imageUrl: "https://m.media-amazon.com/images/I/71gbTink8HL._AC_SX466_.jpg",
    ecoRating: 4.2,
  ),
];