import 'package:greend/products/product_model.dart';

final List<Product> pantShortsProducts = [
  Product(
    id: 51,
    name: "Wrangler Authentics Mens Regular Fit Comfort Flex Waist Jean",
    category: "Pant/Shorts",
    description: "Regular fit jeans with comfort flex waist by Wrangler Authentics.",
    company: "Wrangler Authentic",
    ingredients: [], 
    price: 43.62, 
    imageUrl: "https://m.media-amazon.com/images/I/61MmC3VF+TL._AC_SY445_.jpg", 
    ecoRating: 0.0,
  ),
  Product(
    id: 52,
    name: "Signature by Levi Strauss & Co. Gold Mens Straight Fit Jeans",
    category: "Pant/Shorts",
    description: "Straight fit jeans from Signature by Levi Strauss & Co. Gold.",
    company: "Signature by Levi Strauss & Co. Gold",
    ingredients: [],
    price: 42.15,
    imageUrl: "https://m.media-amazon.com/images/I/51EZ2m+BWGL._AC_SX466_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 53,
    name: "Rustler Mens Classic Regular Fit",
    category: "Pant/Shorts",
    description: "Classic regular fit pants by Rustler.",
    company: "Rustler",
    ingredients: [],
    price: 26.76,
    imageUrl: "https://m.media-amazon.com/images/I/61ocQfqNIDL._AC_SY445_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 54,
    name: "Amazon Essentials Men's Athletic-Fit Stretch Jean",
    category: "Pant/Shorts",
    description: "Athletic-fit stretch jeans for men by Amazon Essentials.",
    company: "Amazon Essentials",
    ingredients: [],
    price: 37.40,
    imageUrl: "https://m.media-amazon.com/images/I/91MZMCGta6S._AC_SX342_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 55,
    name: "Lee Mens Performance Series Extreme Motion Slim Straight Leg Jean",
    category: "Pant/Shorts",
    description: "Slim straight leg jeans with extreme motion flexibility by Lee.",
    company: "Lee",
    ingredients: [],
    price: 49.73,
    imageUrl: "https://m.media-amazon.com/images/I/716FgEVpEQL._AC_SY445_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 56,
    name: "NY Threads Men's Athletic Shorts Quick Dry Lightweight Running Workout Gym Shorts with Pockets",
    category: "Pant/Shorts",
    description: "Quick-dry lightweight gym and running shorts by NY Threads.",
    company: "NY Threads",
    ingredients: [],
    price: 13.99,
    imageUrl: "https://m.media-amazon.com/images/I/71mvr8w552L._AC_SX679_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 57,
    name: "JMIERR Mens Drawstring Shorts Workout Short Stretch Twill Chino Shorts with Pockets Casual Summer Golf Shorts",
    category: "Pant/Shorts",
    description: "Stretch twill chino shorts with pockets by JMIERR.",
    company: "JMIERR",
    ingredients: [],
    price: 31.99,
    imageUrl: "https://m.media-amazon.com/images/I/61qDyhPekKL._AC_SY741_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 58,
    name: "MOVEUP Men's 2 in 1 Running Shorts Quick Dry Athletic Shorts with Liner, Workout Shorts with Pockets and Towel Loop",
    category: "Pant/Shorts",
    description: "2-in-1 quick-dry athletic shorts with a liner and towel loop by MOVEUP.",
    company: "MOVEUP",
    ingredients: [],
    price: 29.99,
    imageUrl: "https://m.media-amazon.com/images/I/71trtiyNNtL._AC_SX466_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 59,
    name: "HMIYA Men's Casual Sports Quick Dry Workout Running or Gym Training Short with Zipper Pockets",
    category: "Pant/Shorts",
    description: "Quick-dry workout and gym training shorts with zipper pockets by HMIYA.",
    company: "HMIYA",
    ingredients: [],
    price: 19.91,
    imageUrl: "https://m.media-amazon.com/images/I/51g4vNg-E7L._AC_SY606_.jpg",
    ecoRating: 0.0,
  ),
  Product(
    id: 60,
    name: "Everlast Mens Lounge and Casual Shorts",
    category: "Pant/Shorts",
    description: "Lounge and casual shorts by Everlast.",
    company: "Everlast",
    ingredients: [],
    price: 14.97,
    imageUrl: "https://m.media-amazon.com/images/I/81lLYu9bWzL._AC_SY445_.jpg",
    ecoRating: 0.0,
  ),
];