import 'package:greend/products/product_model.dart';

final List<Product> snacksProducts = [
  Product(
    id: 11,
    name: "Cheetos Crunchy Cheese",
    category: "Snacks",
    description: "Crispy and cheesy cornmeal-based snack.",
    company: "Cheetos",
    ingredients: [
      "Cornmeal",
      "Vegetable Oil",
      "Cheddar Cheese",
      "Salt",
      "Whey",
      "Buttermilk",
      "MSG",
      "Natural and Artificial Flavors",
      "Disodium Phosphate",
      "Lactic Acid",
      "Yellow #6",
      "Yellow #5"
    ],
    price: 4.27, 
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_c0e117fd-5c95-49ee-9370-cf46398580df.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 12,
    name: "Old Dutch Cheese Pleesers Corn Snack",
    category: "Snacks",
    description: "Corn-based snack with a cheesy flavor.",
    company: "Old Dutch",
    ingredients: [
      "Cornmeal",
      "Vegetable Oil",
      "Modified Milk Ingredients",
      "Corn Maltodextrin",
      "Salt",
      "Cheddar Cheese Solids",
      "Cornstarch",
      "Enzyme Modified Romano Cheese Solids",
      "High Oleic Sunflower Oil",
      "Monosodium Glutamate",
      "Colour",
      "Sodium Phosphate",
      "Natural Flavour",
      "Citric Acid",
      "Disodium Inosinate",
      "Disodium Guanylate",
      "Lactic Acid"
    ],
    price: 4.33,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_13c80a39-a74f-402e-a575-11702beefa69.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 13,
    name: "Great Value Cheese Puffs",
    category: "Snacks",
    description: "Cheese-flavored cornmeal puffs.",
    company: "Great Value",
    ingredients: [
      "Corn Meal",
      "Vegetable Oil (Canola And/Or Corn And/Or Sunflower Oil)",
      "Seasoning",
      "Modified Milk Ingredients",
      "Corn Maltodextrin",
      "Cheddar Cheese Solids",
      "Flavour",
      "Monosodium Glutamate",
      "Colour",
      "Sodium Phosphate",
      "High Oleic Sunflower Oil",
      "Lactic Acid",
      "Citric Acid",
      "Calcium Lactate",
      "Silicon Dioxide"
    ],
    price: 1.82,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_f7415909-a03c-4435-8e8a-c58364567efa.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 14,
    name: "Reese's Peanut Butter Cup Minis",
    category: "Snacks",
    description: "Miniature peanut butter cups coated in chocolate.",
    company: "Reese's",
    ingredients: [
      "Sugar",
      "Partially Defatted Peanuts",
      "Hydrogenated Vegetable Oil",
      "Corn Syrup Solids",
      "Dextrose",
      "Corn Syrup",
      "Palm Kernel Oil",
      "Salt",
      "Confectioner's Glaze",
      "Modified Cornstarch",
      "Lecithin",
      "Artificial Color",
      "Vanillin",
      "Carnauba Wax",
      "Milk"
    ],
    price: 6.41,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_43f45304-aafb-422d-b552-521628f4ef6b.jpeg",
    ecoRating: 3.8,
  ),
  Product(
    id: 15,
    name: "Nestlé AERO Milk Chocolate Minis",
    category: "Snacks",
    description: "Mini milk chocolate bars with a bubbly texture.",
    company: "Nestlé",
    ingredients: [
      "Milk Chocolate",
      "Sugar",
      "Modified Milk Ingredients",
      "Cocoa Butter",
      "Unsweetened Chocolate",
      "Soy Lecithin",
      "Polyglycerol Polyricinoleate",
      "Natural Flavour"
    ],
    price: 3.58,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_a784a9ff-c1c2-4927-9f8e-8fa633547eea.jpg",
    ecoRating: 4.4,
  ),
  Product(
    id: 16,
    name: "NERDS Big Chewy Sweet & Sour Candy",
    category: "Snacks",
    description: "Sweet and sour chewy candy with a crunchy shell.",
    company: "NERDS",
    ingredients: [
      "Dextrose",
      "Corn Syrup",
      "Sugar",
      "Water",
      "Malic Acid",
      "Cornstarch",
      "Modified Cornstarch",
      "Tapioca Dextrin",
      "Natural Flavours",
      "Carnauba Wax",
      "Colour Added",
      "Blue 1",
      "Red 40 Lake",
      "Yellow 6",
      "Yellow 5"
    ],
    price: 3.79,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_6e182143-7966-410c-bb1a-1af559991ff2.jpeg",
    ecoRating: 3.5,
  ),
  Product(
    id: 17,
    name: "Parle Hide & Seek Chocolate",
    category: "Snacks",
    description: "Chocolate chip cookies with a rich cocoa flavor.",
    company: "Parle",
    ingredients: [
      "Enriched Wheat Flour",
      "Chocolate Chips",
      "Sugar",
      "Palm Oil",
      "Invert Syrup",
      "Leavening",
      "Cocoa Solids",
      "Salt",
      "Artificial Vanilla Flavour",
      "Emulsifier"
    ],
    price: 1.49,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_dd862d6f-0892-43a6-8e74-a233067fc60b.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 18,
    name: "Parle Original Gluco Biscuit",
    category: "Snacks",
    description: "Classic glucose biscuits.",
    company: "Parle",
    ingredients: [
      "Enriched Wheat Flour",
      "Sugar",
      "Palm Oil",
      "Invert Syrup",
      "Salt",
      "Leavening",
      "Skim Milk Powder",
      "Artificial Vanilla Flavour",
      "Enzyme",
      "Emulsifier"
    ],
    price: 1.49,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_cf820f71-db3e-40bb-8ab2-ba61373c5585.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 19,
    name: "Britannia Good Day Cashew Biscuit",
    category: "Snacks",
    description: "Cashew-flavored biscuits with a buttery taste.",
    company: "Britannia",
    ingredients: [
      "Wheat Flour",
      "Sugar",
      "Palm Oil",
      "Cashew (4.5%)",
      "Butter (3%)",
      "Invert Sugar",
      "Whole Milk Powder",
      "Leavening",
      "Salt",
      "Soya Lecithin",
      "Emulsifiers",
      "Artificial Flavours"
    ],
    price: 0.97,
    imageUrl: "https://d2lnr5mha7bycj.cloudfront.net/product-image/file/large_c969d4b5-6c01-44e3-80bd-b4f201725176.jpeg",
    ecoRating: 4.4,
  ),
  Product(
    id: 20,
    name: "Lotus Biscoff Caramelized Biscuit Cookies",
    category: "Snacks",
    description: "Crunchy and caramelized biscuit cookies with a unique taste.",
    company: "Lotus Biscoff",
    ingredients: [
      "Wheat Flour",
      "Sugar",
      "Vegetable Oils (Palm*, Rapeseed)",
      "Candy Sugar Syrup",
      "Raising Agent (Sodium Hydrogen Carbonate)",
      "Soya Flour",
      "Salt",
      "Cinnamon"
    ],
    price: 4.34,
    imageUrl: "https://www.instacart.com/assets/domains/product-image/file/large_2b9900f7-068b-4ff7-a964-501168d051c2.PNG",
    ecoRating: 4.5,
  ),
];