import 'package:greend/products/product_model.dart';

final List<Product> socksShoesProducts = [
  Product(
    id: 61,
    name: "Hanes mens Red Label Pack of 6 Cushion Crew Socks",
    category: "Socks/Shoes",
    description: "Pack of 6 cushion crew socks for men by Hanes.",
    company: "Hanes",
    ingredients: [],
    price: 10.97, 
    imageUrl: "https://m.media-amazon.com/images/I/81amTlqc3oL._AC_SX679_.jpg", 
    ecoRating: 4.9,
  ),
  Product(
    id: 62,
    name: "Dickies Men's Dri-tech Moisture Control Crew Socks Multipack, Solid Black (6 Pairs), Shoe Size: 6-12",
    category: "Socks/Shoes",
    description: "Moisture control crew socks in a multipack by Dickies.",
    company: "Dickies",
    ingredients: [],
    price: 19.63,
    imageUrl: "https://m.media-amazon.com/images/I/81LePpXsffL._AC_SX679_.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 63,
    name: "PUMA mens Men's 6 Pack Crew Socks",
    category: "Socks/Shoes",
    description: "6-pack of crew socks for men by PUMA.",
    company: "PUMA",
    ingredients: [],
    price: 26.99,
    imageUrl: "https://m.media-amazon.com/images/I/91QOU93IOrL._AC_SX679_.jpg",
    ecoRating: 5.1,
  ),
  Product(
    id: 64,
    name: "XIUYANG 5 Pairs Cute Smiling Face Socks Embroidery Ankle Novelty Funny Socks Gifts for Womens Socks, Multicolor-2, One Size",
    category: "Socks/Shoes",
    description: "5 pairs of cute smiling face embroidered socks by XIUYANG.",
    company: "XIUYANG",
    ingredients: [],
    price: 16.89,
    imageUrl: "https://m.media-amazon.com/images/I/61JdB7cGDdL._AC_SX466_.jpg",
    ecoRating: 4.6,
  ),
  Product(
    id: 65,
    name: "Timberland PRO mens 6-pack Crew Socks",
    category: "Socks/Shoes",
    description: "6-pack of crew socks for men by Timberland PRO.",
    company: "Timberland PRO",
    ingredients: [],
    price: 31.00,
    imageUrl: "https://m.media-amazon.com/images/I/61ib0kscosL._AC_SX679_.jpg",
    ecoRating: 5.4,
  ),
  Product(
    id: 66,
    name: "Tommy Hilfiger mens Pandora",
    category: "Socks/Shoes",
    description: "Pandora socks for men by Tommy Hilfiger.",
    company: "Tommy Hilfiger",
    ingredients: [],
    price: 66.80,
    imageUrl: "https://m.media-amazon.com/images/I/71XVCaJjJML._AC_SX500_.jpg",
    ecoRating: 4.9,
  ),
  Product(
    id: 67,
    name: "Bruno Marc Men's KnitFlex Breeze Running Walking Shoes Mesh Lightweight Breathable Casual Fashion Sneakers",
    category: "Socks/Shoes",
    description: "Lightweight and breathable casual fashion sneakers by Bruno Marc.",
    company: "Bruno Marc",
    ingredients: [], 
    price: 65.99,
    imageUrl: "https://m.media-amazon.com/images/I/711lA5rk08L._AC_SY500_.jpg",
    ecoRating: 5.0,
  ),
  Product(
    id: 68,
    name: "Under Armour Mens Charged Commit Trainer 4 Sneaker",
    category: "Socks/Shoes",
    description: "Charged Commit Trainer 4 sneakers for men by Under Armour.",
    company: "Under Armour",
    ingredients: [],
    price: 75.0,
    imageUrl: "https://m.media-amazon.com/images/I/51-rANf+9GL._AC_SX500_.jpg",
    ecoRating: 5.6,
  ),
  Product(
    id: 69,
    name: "adidas Mens Run Falcon 5 Sneaker",
    category: "Socks/Shoes",
    description: "Run Falcon 5 sneakers for men by adidas.",
    company: "Adidas",
    ingredients: [],
    price: 88.25,
    imageUrl: "https://m.media-amazon.com/images/I/516q+jjLYsL._AC_SY500_.jpg",
    ecoRating: 5.8,
  ),
  Product(
    id: 70,
    name: "Reebok Mens Lite 4 Sneaker",
    category: "Socks/Shoes",
    description: "Lite 4 sneakers for men by Reebok.",
    company: "Reebok",
    ingredients: [],
    price: 51.71,
    imageUrl: "https://m.media-amazon.com/images/I/71jKYOj1BGL._AC_SX500_.jpg",
    ecoRating: 5.4,
  ),
];