import 'package:greend/products/product_model.dart';

final List<Product> womenShirtsProducts = [
  Product(
    id: 31,
    name: "Feiersi Women's Off Shoulder Sweater Casual Long Sleeve Crew Neck Tops Loose Pullover Knit Jumper",
    category: "Shirts - Women",
    description: "Casual long sleeve crew neck pullover knit jumper by Feiersi.",
    company: "Feiersi",
    ingredients: [], 
    price: 49.99, 
    imageUrl: "https://m.media-amazon.com/images/I/71fTtqTCpSL._AC_SX679_.jpg",
    ecoRating: 4.4, 
  ),
  Product(
    id: 32,
    name: "CHICALLURE Womens Off The Shoulder Tops Long Sleeve Pullover Sweatshirt Sweater Casual Loose Blouse Tunic Shirt",
    category: "Shirts - Women",
    description: "Loose and casual off-the-shoulder pullover by CHICALLURE.",
    company: "CHICALLURE",
    ingredients: [],
    price: 34.99,
    imageUrl: "https://m.media-amazon.com/images/I/815RzZpLPIL._AC_SY550_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 33,
    name: "Eniloyal Off The Shoulder Tops for Women Long Sleeve Shirt Cotton Batwing Trendy Going Out Fall Clothing Oversized Tshirt",
    category: "Shirts - Women",
    description: "Trendy off-the-shoulder oversized T-shirt for women by Eniloyal.",
    company: "Eniloyal",
    ingredients: [],
    price: 32.99,
    imageUrl: "https://m.media-amazon.com/images/I/51L1p0BMsBL._AC_SY445_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 34,
    name: "Jouica Women's Summer Cold Shoulder Tops Mesh Panel 3/4 Bell Sleeve Tees Adjustable Spaghetti Strap Loose Fit Shirts",
    category: "Shirts - Women",
    description: "Summer cold shoulder tops with bell sleeves by Jouica.",
    company: "Jouica",
    ingredients: [],
    price: 29.99,
    imageUrl: "https://m.media-amazon.com/images/I/71Nk56b3NLL._AC_SY445_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 35,
    name: "Florboom Womens Tshirt Casual Cold Shoulder Loose Fit Long T Shirts",
    category: "Shirts - Women",
    description: "Casual cold shoulder loose fit long T-shirt for women by Florboom.",
    company: "Florboom",
    ingredients: [],
    price: 29.98,
    imageUrl: "https://m.media-amazon.com/images/I/61KK5CsoSNL._AC_SY445_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 36,
    name: "Decrum Raglan Shirt Women - 3/4 Sleeves Casual Fashion Baseball Tops & Tees",
    category: "Shirts - Women",
    description: "Casual fashion baseball top with raglan sleeves by Decrum.",
    company: "Decrum",
    ingredients: [],
    price: 26.95,
    imageUrl: "https://m.media-amazon.com/images/I/81mCRDmAalL._AC_SX466_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 37,
    name: "3/4 Length Sleeve Womens Tops Dressy Casual Floral Print Crewneck Tshirt Tunic Tops Blouse Loose Shirt Graphic Tees",
    category: "Shirts - Women",
    description: "Dressy casual floral print crewneck tunic top for women.",
    company: "Generic",
    ingredients: [],
    price: 14.32,
    imageUrl: "https://m.media-amazon.com/images/I/61FjF4p0awL._AC_SX466_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 38,
    name: "ORANDESIGNE Women's 3/4 Sleeves V Neck T Shirts Color Block Casual Summer Tops Fashion Loose Shirts Tees",
    category: "Shirts - Women",
    description: "Color block casual summer V-neck shirt by ORANDESIGNE.",
    company: "ORANDESIGNE",
    ingredients: [],
    price: 17.27,
    imageUrl: "https://m.media-amazon.com/images/I/61-fqLsz8qL._AC_SY445_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 39,
    name: "JINKESI Women's Casual Elegant 3/4 Lace Sleeve Round Neck Solid Color Summer Loose Fit T Shirts Tops Blouses",
    category: "Shirts - Women",
    description: "Casual elegant T-shirt with lace sleeves by JINKESI.",
    company: "JINKESI",
    ingredients: [],
    price: 19.97,
    imageUrl: "https://m.media-amazon.com/images/I/51C1HviZe4L._AC_SX425_.jpg",
    ecoRating: 4.3, 
  ),
  Product(
    id: 40,
    name: "COSSEN Womens Tops Dressy Casual Shirt 3/4 Sleeve V Neck Blouses Zipper Collar Women Polo Shirts",
    category: "Shirts - Women",
    description: "Dressy casual V-neck blouse with zipper collar by COSSEN.",
    company: "COSSEN",
    ingredients: [],
    price: 29.99,
    imageUrl: "https://m.media-amazon.com/images/I/81vFyrDtNsL._AC_SY445_.jpg",
    ecoRating: 4.3, 
  ),
];